//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class management
    {
        public int id { get; set; }
        public string roomno { get; set; }
        public string products { get; set; }
        public string productmodel { get; set; }
        public string available { get; set; }
    }
}
